--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/OmChendvankar/ADVBlackMarket
build-by-default: true
branches:
- main
projects:
  BlackMarket:
    path: ""
    icon: "icon.png"
    libs:
    - src: muqsit/InvMenu/InvMenu
      branch: master
      version: ^4.1.1
...
