-----
name: BlackMarket
main: om\BlackMarket
author: Om
api: 3.0.0
version: 1.0.0
depend:
- EconomyAPI

commands: 
  blackmarket:
    description: "Opens BlackMarket menu"
    aliases: [bm]
  removecooldown:
    description: "Removes Cooldown"
    aliases: [rcd]
    permission: blackmarket.removes.cooldown

permissions:
  blackmarket.remove.cooldown:
    description: removes cooldown
    default: op