#Items you want to put in the BlackMarket
#you have to mention the Id,Metadata and amount of the specfic item you can refer to https://minecraft-ids.grahamedgecombe.com/
#ByDefault its Wooden, Iron and Diamond Sword as Item1,Item2 and Item3 respectively.
#Item1 Data
Item1_Id: 268
Item1_Meta: 0
Item1_Amt: 1
#Item2 Data
Item2_Id: 267
Item2_Meta: 0
Item2_Amt: 1
#Item3 Data
Item3_Id: 276
Item3_Meta: 0
Item3_Amt: 1

#Cost of the Item you put in BlackMarket
#Cost of Item1
Cost1: 10
#Cost of Item2
Cost2: 10
#Cost of Item3
Cost3: 10